=== ixnode/php-json-schema-validator/data/json/schema/complex.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "Used for validation of data/json/raw/complex.json JSON file.",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "version": {
      "type": "string",
      "pattern": "^\\d.\\d.\\d$"
    },
    "type": {
      "type": "string",
      "enum": [
        "apiEndpoint"
      ]
    },
    "forms": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "customer-type": {
            "type": "string",
            "enum": [
              "private",
              "business"
            ]
          },
          "product-type": {
            "type": "string",
            "enum": [
              "power",
              "gas"
            ]
          },
          "name": {
            "type": "string",
            "pattern": "^[0-9]{5}$"
          },
          "type": {
            "type": "string",
            "enum": [
              "form",
              "summary"
            ]
          },
          "action": {
            "type": [
              "string",
              "null"
            ],
            "pattern": "^/api/v1/form/[0-9]+/[0-9]{5}$",
            "description": "Specifies the API endpoint where the values entered by the user are passed.",
            "examples": [
              "/api/v1/form/323/00001",
              "/api/v1/form/323/00002",
              "/api/v1/form/323/00003",
              "/api/v1/form/323/00004",
              "/api/v1/form/3/00001",
              "/api/v1/form/3/00002",
              "/api/v1/form/3/00003",
              "/api/v1/form/3/00004"
            ]
          },
          "request": {
            "oneOf": [
              {
                "type": "string",
                "enum": [
                  "POST",
                  "GET"
                ],
                "description": "Specifies the request method used to serve the API endpoint (action).",
                "examples": [
                  "POST",
                  "GET"
                ]
              },
              {
                "type": "null"
              }
            ]
          },
          "order": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "content": {
            "type": "object",
            "patternProperties": {
              "^.*$": {
                "type": "object",
                "properties": {
                  "order": {
                    "type": "integer",
                    "minimum": 0
                  },
                  "group": {
                    "type": "string",
                    "enum": [
                      "Form1"
                    ]
                  },
                  "name": {
                    "type": "string",
                    "pattern": "^[a-z][0-9a-zA-Z]+$",
                    "minLength": 3,
                    "maxLength": 255
                  },
                  "caption": {
                    "type": [
                      "string",
                      "null"
                    ],
                    "minLength": 3,
                    "maxLength": 255
                  },
                  "description": {
                    "type": [
                      "string",
                      "null"
                    ],
                    "minLength": 3,
                    "maxLength": 65535
                  },
                  "event": {
                    "type": "string",
                    "enum": [
                      "input",
                      "submit",
                      "view",
                      "link",
                      "ajax"
                    ]
                  },
                  "field": {
                    "type": "string",
                    "enum": [
                      "choice",
                      "choice-slider",
                      "select",
                      "select-autocomplete",
                      "radio",
                      "radio-zoned",
                      "text",
                      "checkbox",
                      "button",
                      "date",
                      "date-limited",
                      "html",
                      "link",
                      "iban-wizard"
                    ]
                  },
                  "schema": {
                    "$ref": "#/$defs/schema"
                  },
                  "dependencies": {
                    "type": [
                      "array",
                      "null"
                    ],
                    "items": {
                      "$ref": "#/$defs/dependency"
                    }
                  },
                  "method": {
                    "type": "string",
                    "description": "Specifies an additional method to check the passed value (PHP + JS)."
                  },
                  "data": {
                    "type": "object",
                    "properties": {
                      "choice": {
                        "type": [
                          "object",
                          "array"
                        ],
                        "patternProperties": {
                          "^.*$": {
                            "type": [
                              "string",
                              "integer",
                              "object"
                            ],
                            "properties": {
                              "title": {
                                "type": "string"
                              },
                              "description": {
                                "type": "string"
                              },
                              "value": {
                                "type": ["string", "integer"]
                              }
                            },
                            "additionalItems": false,
                            "required": ["title", "description", "value"]
                          }
                        },
                        "items": {
                          "type": [
                            "string",
                            "integer",
                            "object"
                          ],
                          "properties": {
                            "title": {
                              "type": "string"
                            },
                            "description": {
                              "type": "string"
                            },
                            "value": {
                              "type": ["string", "integer"]
                            }
                          },
                          "additionalItems": false,
                          "required": ["title", "description", "value"]
                        }
                      },
                      "choiceApi": {
                        "type": "object",
                        "properties": {
                          "endpoint": {
                            "type": "string"
                          },
                          "endpoints": {
                            "type": "object"
                          },
                          "options": {
                            "type": "array",
                            "minItems": 1
                          },
                          "labels": {
                            "type": "array",
                            "minItems": 1
                          },
                          "defaults": {
                            "type": "object"
                          }
                        },
                        "required": [
                          "endpoint",
                          "options",
                          "labels"
                        ],
                        "additionalProperties": false
                      },
                      "link": {
                        "type": "object",
                        "properties": {
                          "url": {
                            "type": "string"
                          },
                          "caption": {
                            "type": "string"
                          }
                        },
                        "required": [
                          "url",
                          "caption"
                        ],
                        "additionalProperties": false
                      },
                      "paymentData": {
                        "type": "object"
                      },
                      "userData": {
                        "type": "object"
                      },
                      "orderData": {
                        "type": "object"
                      },
                      "additional": {
                        "type": "object",
                        "properties": {
                          "title": {
                            "type": "string"
                          },
                          "description": {
                            "type": "string"
                          }
                        },
                        "additionalProperties": false
                      },
                      "benefits": {
                        "type": "array",
                        "items": {
                          "type": "object",
                          "properties": {
                            "title": {
                              "type": "string"
                            },
                            "text": {
                              "type": "string"
                            },
                            "icon": {
                              "type": "string"
                            }
                          },
                          "additionalProperties": false,
                          "required": ["title", "text", "icon"]
                        }
                      },
                      "teaser": {
                        "type": "object",
                        "properties": {
                          "title": {
                            "type": ["string", "null"]
                          },
                          "description": {
                            "type": ["string", "null"]
                          }
                        },
                        "additionalProperties": false
                      },
                      "tariff": {
                        "type": [
                          "object",
                          "array"
                        ]
                      },
                      "summary": {
                        "type": "object"
                      },
                      "supplier": {
                        "type": [
                          "object",
                          "array"
                        ]
                      }
                    },
                    "additionalProperties": false
                  },
                  "required": {
                    "type": [
                      "boolean",
                      "null",
                      "array"
                    ],
                    "items": [
                      {
                        "type": "boolean"
                      },
                      {
                        "type": "string"
                      }
                    ],
                    "description": "Specifies, if the field is required (boolean: true, false). You can also use conditions (array: [required, condition])."
                  },
                  "readonly": {
                    "type": "boolean"
                  },
                  "default": {
                    "type": "object",
                    "properties": {
                      "value": {
                        "type": [
                          "integer",
                          "string",
                          "null"
                        ]
                      },
                      "method": {
                        "type": "string"
                      }
                    },
                    "required": [
                      "value"
                    ],
                    "additionalProperties": false
                  },
                  "current": {
                    "type": "object",
                    "properties": {
                      "value": {
                        "type": [
                          "integer",
                          "string",
                          "null"
                        ]
                      }
                    },
                    "required": [
                      "value"
                    ],
                    "additionalProperties": false
                  },
                  "unit": {
                    "type": [
                      "string",
                      "null"
                    ]
                  },
                  "validator": {
                    "type": "string"
                  }
                },
                "required": [
                  "order",
                  "group",
                  "name",
                  "caption",
                  "description",
                  "event",
                  "field",
                  "schema",
                  "dependencies",
                  "required",
                  "readonly",
                  "default",
                  "current",
                  "unit"
                ],
                "additionalProperties": false
              }
            }
          },
          "schema": {
            "oneOf": [
              {
                "$ref": "http://json-schema.org/draft-07/schema#"
              },
              {
                "type": "null"
              }
            ]
          }
        },
        "required": [
          "customer-type",
          "product-type",
          "name",
          "type",
          "action",
          "request",
          "order",
          "content",
          "schema"
        ],
        "additionalProperties": false
      }
    }
  },
  "required": [
    "$schema",
    "description",
    "version",
    "type",
    "forms"
  ],
  "additionalProperties": false,
  "$defs": {
    "schema": {
      "type": "object",
      "properties": {
        "oneOf": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/schema"
          }
        },
        "type": {
          "type": "string",
          "enum": [
            "integer",
            "string",
            "null",
            "object"
          ]
        },
        "enum": {
          "type": "array",
          "items": {
            "type": [
              "string",
              "integer"
            ]
          },
          "uniqueItems": true
        },
        "minimum": {
          "type": "integer"
        },
        "maximum": {
          "type": "integer"
        },
        "minLength": {
          "type": "integer"
        },
        "maxLength": {
          "type": "integer"
        },
        "format": {
          "type": "string",
          "enum": [
            "email",
            "date"
          ]
        },
        "pattern": {
          "type": "string",
          "description": "Specifies a regular string for checking the passed value (PHP + JS)."
        }
      },
      "required": [],
      "additionalProperties": false
    },
    "dependency": {
      "type": "object",
      "properties": {
        "description": {
          "type": "string"
        },
        "allOf": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/dependency"
          }
        },
        "oneOf": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/dependency"
          }
        },
        "anyOf": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/dependency"
          }
        },
        "if": {
          "type": "object"
        },
        "then": {
          "type": "object"
        },
        "else": {
          "type": "object"
        },
        "required": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": [],
      "additionalProperties": false
    }
  }
}

=== ixnode/php-json-schema-validator/data/json/raw/complex.json
{
    "$schema": "../schema/complex.json",
    "description": "This schema document describes the API endpoint '/api/v1/form/'.",
    "version": "1.0.0",
    "type": "apiEndpoint",
    "forms": [
        {
            "customer-type": "private",
            "product-type": "power",
            "name": "00001",
            "type": "form",
            "action": "/api/v1/form/323/00001",
            "request": "POST",
            "order": [
                "deliveryZipCode",
                "operator",
                "button"
            ],
            "content": {
                "deliveryZipCode": {
                    "order": 0,
                    "group": "Form1",
                    "name": "deliveryZipCode",
                    "caption": "<translate>",
                    "description": null,
                    "event": "input",
                    "field": "text",
                    "schema": {
                        "type": "string",
                        "pattern": "^[0-9]{5}$",
                        "minLength": 5,
                        "maxLength": 5
                    },
                    "dependencies": null,
                    "method": "checkZipCode()",
                    "required": true,
                    "readonly": false,
                    "default": {
                        "value": null
                    },
                    "current": {
                        "value": null
                    },
                    "unit": null
                },
                "operator": {
                    "order": 1,
                    "group": "Form1",
                    "name": "operator",
                    "caption": "<translate>",
                    "description": null,
                    "event": "input",
                    "field": "select",
                    "schema": {
                        "type": "string",
                        "pattern": "^[0-9]{13}$"
                    },
                    "dependencies": null,
                    "required": true,
                    "readonly": false,
                    "default": {
                        "value": null
                    },
                    "current": {
                        "value": null
                    },
                    "unit": null
                },
                "button": {
                    "order": 2,
                    "group": "Form1",
                    "name": "button",
                    "caption": "<translate>",
                    "description": null,
                    "event": "submit",
                    "field": "button",
                    "schema": {
                        "type": "integer",
                        "enum": [
                            1
                        ]
                    },
                    "dependencies": null,
                    "required": true,
                    "readonly": false,
                    "default": {
                        "value": 1
                    },
                    "current": {
                        "value": 1
                    },
                    "unit": null
                }
            },
            "schema": {
                "$schema": "http://json-schema.org/draft-07/schema#",
                "description": "Used for validation of data/json/raw/complex.json JSON file.",
                "type": "object",
                "additionalProperties": false,
                "properties": {
                    "deliveryZipCode": {
                        "type": "string",
                        "pattern": "^[0-9]{5}$",
                        "minLength": 5,
                        "maxLength": 5
                    },
                    "operator": {
                        "type": "string",
                        "pattern": "^[0-9]{13}$"
                    },
                    "button": {
                        "type": "integer",
                        "enum": [
                            1
                        ]
                    }
                },
                "required": [
                    "deliveryZipCode",
                    "operator",
                    "button"
                ]
            }
        }
    ]
}
