=== ixnode/php-json-schema-validator/data/json/schema/simple.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "description": "Used for validation of data/json/raw/complex.json JSON file.",
    "type": "object",
    "properties": {
        "$schema": {
            "type": "string"
        },
        "name": {
            "type": "string"
        },
        "description": {
            "type": "string"
        },
        "version": {
            "type": "string",
            "pattern": "^[0-9]+\\.[0-9]+\\.[0-9]+$"
        },
        "date": {
            "type": "string"
        },
        "license": {
            "type": "string"
        },
        "authors": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "php-version": {
            "type": "string",
            "pattern": "^[0-9]+\\.[0-9]+\\.[0-9]+$"
        },
        "symfony-version": {
            "type": "string",
            "pattern": "^[0-9]+\\.[0-9]+\\.[0-9]+$"
        }
    },
    "additionalProperties": false,
    "required": [
        "name",
        "description",
        "version",
        "date",
        "license",
        "authors",
        "php-version",
        "symfony-version"
    ]
}

=== ixnode/php-json-schema-validator/data/json/raw/simple.json
{
    "$schema": "../schema/simple.json",
    "name": "twelvepics-com/php-holiday-db",
    "description": "Provides an API for holidays.",
    "version": "0.1.0",
    "date": "Friday, December 30, 2022 - 10:45:29",
    "license": "Copyright (c) 2022 Björn Hempel",
    "authors": [
        "Björn Hempel <bjoern@hempel.li>"
    ],
    "php-version": "8.1.13",
    "symfony-version": "6.2.1"
}
